package com.esprit.formulaire;


import com.codename1.components.OnOffSwitch;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.ui.Button;
import com.codename1.ui.CheckBox;
import com.codename1.ui.Container;
import com.codename1.ui.TextField;
import com.codename1.ui.Toolbar;
import com.codename1.ui.events.ActionEvent;
import com.codename1.ui.events.ActionListener;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.ui.spinner.Picker;
import com.esprit.formulaire.gui.LeftoversListForm;
import com.esprit.formulaire.gui.OrganisationListForm;
import java.io.IOException;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class MyApplication {

    private Form current;
    private Resources theme;

    public void init(Object context) {
        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature, uncomment if you have a pro subscription
        // Log.bindCrashProtection(true);
    }
    
    public void start() {
        
        
         new OrganisationListForm().show();
      /*  TextField tfNom = new TextField("", "Nom");
        TextField tfPrenom = new TextField("", "Prenom");
        TextField tfPwd =  new TextField("","Password");
        Picker date =new Picker();
        tfPwd.setConstraint(TextField.PASSWORD);     
        
        Container c = new Container(BoxLayout.x());
        Label l = new Label("Gender : ");
        OnOffSwitch onOff = new OnOffSwitch();    
        
        c.add(l);
        c.add(onOff);  
       
        CheckBox chFoot = new CheckBox("Foot");
        CheckBox chTennis = new CheckBox("Tennis");
        CheckBox chLecture = new CheckBox("Lecture");
        CheckBox chNatation = new CheckBox("Swiming");
        
        Button btnValider = new Button("Valider");    
        
        f.add(tfNom);
        f.add(tfPrenom);
        f.add(tfPwd);
        f.add(date);
        f.add(c);
        f.add(chFoot);
        f.add(chTennis);
        f.add(chLecture);
        //f.add(chwiming);
        f.add(btnValider);
        
        f.show();
        
        btnValider.addActionListener(new ActionListener() {

          @Override
          public void actionPerformed(ActionEvent evt) {
         Form f2 = new Form(BoxLayout.y());
         Label lNom = new Label("Nom : "+ tfNom.getText());
         Label lPrenom = new Label("Prenom : "+ tfPrenom.getText());
         Label lPwd = new Label("Password : "+ tfPwd.getText());
         Label lDate= new Label("Date : "+ date.getDate().toString());
         
         Label lGender = new Label("Gender : ");
          
         if(onOff.isValue())lGender.setText("Gender : Homme");
         else lGender.setText("Gender : Femme");
         Label lHobis = new Label();
         String ch ="Hobis : ";
         if(chFoot.isSelected())ch+= " foot,";
         if(chTennis.isSelected())ch+= " tennis,";
         if(chLecture.isSelected())ch+= " Lecture,";
         if(chNatation.isSelected())ch+= " swiming,";
         lHobis.setText(ch);
         f2.add(lNom);
         f2.add(lPrenom);
         f2.add(lPwd);
         f2.add(lDate);
         f2.add(lGender);
         f2.add(lHobis);
         f2.show();
         
          }
      });
        
        
        
        */
        
                
      
      
    }

    public void stop() {
        current = Display.getInstance().getCurrent();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = Display.getInstance().getCurrent();
        }
    }
    
    public void destroy() {
    }

}
